### PR TITLE
Write property f64

### PR DESCRIPTION
**Pull request by heestree**
Write property f64

### CODE REVIEW

**Comment by jrmuizel** [comment]
Can you remove the README related commits?

**Comment by heestree** [comment]
No README in pull request (it's been removed before PR). Only two files (lib.rs and parser.rs) are updated.

**Comment by heestree** [comment]
BTW, thanks for etw-reader. It's been great help for my project. I hope this repo grows up to production level.

**Comment by mstange** [comment]
> No README in pull request (it's been removed before PR). Only two files (lib.rs and parser.rs) are updated.

Github pull requests always contain the full delta of changes between the pushed branch and the reference branch (here the main branch). You can see all commits that are included in this PR by going to the "Commits" tab.
To create a more focused pull request, you need to create a new branch which is based on this repo's main branch and only has the change you want to propose for inclusion.

**Pull request closed without merging**
